services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wizard_game_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "5173:5173" # Expose Vite dev server port
    environment:
      - APP_ENV=${APP_ENV:-local}
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: wizard_game_web
    restart: unless-stopped
    ports:
      - "1012:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: wizard_game_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-wizard_board}
      MYSQL_USER: ${DB_USERNAME:-wizard_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.4-alpine
    container_name: wizard_game_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
